os: linux

language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - black .
  - python -m black . --check
  - flake8 mysite
  - python -m coverage run --source='.' manage.py test

after_success:
  - coveralls

before_deploy: "echo 'ready?'"

